=== nbouherrou/Web-Service/client.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="client">
      <xs:complexType>
        <xs:sequence>

          <xs:element name="name" type="xs:string" />

          <xs:element name="age" type="xs:integer">
            <xs:simpleType>
              <xs:restriction base="xs:integer">
                <xs:minInclusive value="12"/>
                <xs:maxInclusive value="120"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>

          <xs:element name="address">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="street" type="xs:string"/>
                <xs:element name="city" type="xs:string"/>
                <xs:element name="department" type="xs:string"/>
                <xs:element name="postal-code" type="xs:decimal"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

        </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:schema>

=== nbouherrou/Web-Service/client.xml
<?xml version="1.0" encoding="UTF-8"?>
  <client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="client.xsd">

    <name>Jean</name>

    <age>12</age>

    <address>
      <street>Jacquard</street>
      <city>St Etienne</city>
      <department>Rhone</department>
      <postal-code>42000</postal-code>
    </address>

  </client>
